# Site settings
title: Custom Success Specialist Page
email: michael@formationtech.com
description: > # this means to ignore newlines until "baseurl:"
  This site is a dedicated page for an application assigment for the position of
  Customer Support Specialist position with ShopStorm
baseurl: ""
url: "http://rawbee3d/rawbee3d.github.io"
twitter_username: rawbee3d
github_username:  rawbee3d

markdown:
